# Extracción de datos TikTok - Lululemon por Hashtags

Se buscan vídeos de TikTok relacionados con Lululemon a partir de hashtags.
Se extraen los vídeos con más engagement y luego se descargan los comentarios de los top vídeos.

**Dos zonas geográficas** para análisis comparativo:
- Estados Unidos (US) — comentarios en inglés
- Europa (ES, FR, GB, DE) — comentarios filtrados por idioma del país

**Filtrado por idioma:**
- US (proxy US) → solo inglés
- España (proxy ES) → solo español
- Francia (proxy FR) → solo francés
- Reino Unido (proxy GB) → solo inglés
- Alemania (proxy DE) → solo alemán

**Actores de Apify:**
- `apidojo/tiktok-scraper` — búsqueda por hashtags con filtro de `location`
- `clockworks/tiktok-comments-scraper` — extracción de comentarios

In [1]:
pip install apify-client pandas langdetect

Requirement already satisfied: apify-client in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (2.5.0)
Requirement already satisfied: pandas in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (3.0.1)
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 27.7 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: apify-shared<3.0.0,>=2.1.0 in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (from apify-client) (2.2.0)
Requirement already satisfied: colorama>=0.4.0 in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (from apify-client) (0.4.6)
Requirement already satisfied: impit>=0.9.2 in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (from apify-client) (0.12.0)
Requirement already satisfied: more-itertools>=10.0.0 in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (from apify-client) (10.8.0)
Requirement already satisfied: numpy>=1.26.0 in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six in /Users/gonzaloalonsolidon/Desktop/Repos/Cursor/analitica-social-final/.venv/lib/python3.11/site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (pyproject.toml) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993332 sha256=fbb9dbfb1852be86500b95ecf2f86a370a30c52374b6c64803716e2751cd24d6
  Stored in directory: /Users/gonzaloalonsolidon/Library/Caches/pip/wheels/0a/f2/b2/e5ca405801e05eb7c8ed5b3b4bcf1fcabcd6272c167640072e
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from apify_client import ApifyClient
import pandas as pd
import json
from langdetect import detect, LangDetectException

from dotenv import load_dotenv
import os

load_dotenv()
APIFY_TOKEN = os.getenv("APIFY_TOKEN")
client = ApifyClient(APIFY_TOKEN)

In [ ]:
# Hashtags relacionados con Lululemon
HASHTAGS = [
    "lululemon",
    "lululemonhaul",
    "lululemonreview",
    "lululemonfavorites",
    "lululemonoutfit",
    "lululemonleggings",
    "lululemontryhaul",
    "lululemonfinds",
]

HASHTAG_URLS = [{"url": f"https://www.tiktok.com/tag/{h}"} for h in HASHTAGS]
print(f"Total hashtags: {len(HASHTAG_URLS)}")
for u in HASHTAG_URLS:
    print(f"  {u['url']}")

Total hashtags: 8
  https://www.tiktok.com/tag/lululemon
  https://www.tiktok.com/tag/lululemonhaul
  https://www.tiktok.com/tag/lululemonreview
  https://www.tiktok.com/tag/lululemonfavorites
  https://www.tiktok.com/tag/lululemonoutfit
  https://www.tiktok.com/tag/lululemonleggings
  https://www.tiktok.com/tag/lululemontryhaul
  https://www.tiktok.com/tag/lululemonfinds

---
## 1. Funciones auxiliares

In [4]:
def build_post_url(row):
    """Construye la URL del post a partir de channel.username e id."""
    channel = row.get("channel")
    video_id = row.get("id")
    if isinstance(channel, dict) and channel.get("username") and video_id:
        return f"https://www.tiktok.com/@{channel['username']}/video/{video_id}"
    return None

def procesar_videos(items):
    """Convierte los items del actor a DataFrame con score y ranking."""
    df = pd.DataFrame(items)
    if len(df) == 0:
        return df
    for col in ["likes", "comments", "shares", "views", "bookmarks"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    df["post_url"] = df.apply(build_post_url, axis=1)
    df["author"] = df["channel"].apply(
        lambda c: c.get("username", "") if isinstance(c, dict) else ""
    )
    df["score"] = df["comments"] * 3 + df["likes"] * 1 + df["shares"] * 2
    df = df.sort_values("score", ascending=False).reset_index(drop=True)
    df["rank"] = range(1, len(df) + 1)
    return df

def detectar_idioma(texto):
    """Detecta el idioma de un texto. Devuelve código ISO o 'unknown'."""
    try:
        if not texto or not isinstance(texto, str) or len(texto.strip()) < 3:
            return "unknown"
        return detect(texto)
    except LangDetectException:
        return "unknown"

def filtrar_comentarios_por_idioma(df_comments, idiomas_permitidos):
    """Filtra comentarios por idioma detectado."""
    # Buscar columna de texto del comentario
    col_texto = None
    for c in ["text", "comment", "commentText", "body"]:
        if c in df_comments.columns:
            col_texto = c
            break
    if col_texto is None:
        print("AVISO: No se encontró columna de texto. Columnas:", df_comments.columns.tolist())
        return df_comments
    
    df_comments["idioma_detectado"] = df_comments[col_texto].apply(detectar_idioma)
    
    print(f"Distribución de idiomas detectados:")
    print(df_comments["idioma_detectado"].value_counts().head(10))
    
    df_filtrado = df_comments[df_comments["idioma_detectado"].isin(idiomas_permitidos)].copy()
    print(f"\nComentarios antes del filtro: {len(df_comments)}")
    print(f"Comentarios después del filtro ({', '.join(idiomas_permitidos)}): {len(df_filtrado)}")
    return df_filtrado

print("Funciones cargadas.")

Funciones cargadas.

---
## 2. Extracción de vídeos - Estados Unidos

`location: "US"` — luego los comentarios se filtrarán a solo inglés.

In [5]:
run_us = client.actor("apidojo/tiktok-scraper").call(
    run_input={
        "startUrls": HASHTAG_URLS,
        "maxItems": 200,
        "location": "US",
    }
)

print("Run ID (US):", run_us["id"])
print("Dataset ID (US):", run_us["defaultDatasetId"])

[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> Status: RUNNING, Message:
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:34.469Z ACTOR: Pulling container image of build 1wgxHJCb5SrQmUuTk from registry.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:34.472Z ACTOR: Creating container.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:34.525Z ACTOR: Starting container.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:35.918Z INFO  System info {"apifyVersion":"3.4.2","apifyClientVersion":"2.12.4","crawleeVersion":"3.13.5","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:35.956Z INFO  PHASE -- STARTING ACTOR.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:36.263Z INFO  PHASE -- SETTING UP CRAWLER.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:36.264Z INFO  [Status message]: Your run has started.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:36.305Z WARN  ###############################
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:36.307Z WARN  Your run has started.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:36.308Z WARN  ###############################
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> Status: RUNNING, Message: Your run has started.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:36.310Z INFO  PHASE -- CRAWLER STARTED.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:38.165Z INFO  Got 9 videos for tag lululemonfavorites with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:38.832Z INFO  Got 20 videos for tag lululemonhaul with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:38.836Z INFO  Got 19 videos for tag lululemonreview with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:39.711Z INFO  Got 19 videos for tag lululemon with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:39.974Z INFO  Got 15 videos for tag lululemonfavorites with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:39.993Z INFO  Got 15 videos for tag lululemonfinds with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:40.135Z INFO  Got 18 videos for tag lululemonhaul with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:40.195Z INFO  Got 16 videos for tag lululemontryhaul with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:40.882Z INFO  Got 17 videos for tag lululemonreview with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:41.039Z INFO  Got 6 videos for tag lululemonfinds with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:41.277Z INFO  Got 19 videos for tag lululemonoutfit with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:41.461Z INFO  Got 16 videos for tag lululemonleggings with page: 1
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:41.599Z INFO  Got 15 videos for tag lululemontryhaul with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:41.848Z INFO  Got 14 videos for tag lululemonfavorites with page: 3
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:42.516Z INFO  Got 17 videos for tag lululemonreview with page: 3
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:42.769Z INFO  Got 19 videos for tag lululemonfinds with page: 3
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:42.906Z INFO  Got 19 videos for tag lululemonleggings with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:43.289Z INFO  Got 20 videos for tag lululemonhaul with page: 3
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:43.492Z INFO  Got 20 videos for tag lululemon with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:44.328Z INFO  Got 17 videos for tag lululemonoutfit with page: 2
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> 2026-03-26T12:42:44.330Z INFO  [Status message]: Your run has finished.
[apify.tiktok-scraper runId:TjOOACa1Qp9kGXXbu] -> Status: SUCCEEDED, Message: Your run has finished.

Run ID (US): TjOOACa1Qp9kGXXbu
Dataset ID (US): sipR2nq5Gi8QAXZPq

In [6]:
items_us = list(client.dataset(run_us["defaultDatasetId"]).iterate_items())
print(f"Total vídeos US: {len(items_us)}")

df_us = procesar_videos(items_us)

print(f"\nTop 10 US por engagement:")
df_us[["rank", "author", "likes", "comments", "shares", "views", "score", "post_url"]].head(10)

Total vídeos US: 200

Top 10 US por engagement:

,rank,author,likes,comments,shares,views,score,post_url
0,1,huntercamp33,608149,482,1850,5371145,613295,https://www.tiktok.com/@huntercamp33/video/720...
1,2,lisi.shops,579366,2092,7022,5543233,599686,https://www.tiktok.com/@lisi.shops/video/72669...
2,3,tiktokwithtay,404703,236,207,7691473,405825,https://www.tiktok.com/@tiktokwithtay/video/69...
3,4,8kzayy,257312,2692,49366,1612464,364120,https://www.tiktok.com/@8kzayy/video/761988239...
4,5,bellagiannop,331023,1589,934,2448898,337658,https://www.tiktok.com/@bellagiannop/video/711...
5,6,rose32xz,288127,856,1306,4841820,293307,https://www.tiktok.com/@rose32xz/video/7552319...
6,7,courtneyycahoon,282257,655,2631,1533658,289484,https://www.tiktok.com/@courtneyycahoon/video/...
7,8,sophiasouzas,237276,430,3301,2301334,245168,https://www.tiktok.com/@sophiasouzas/video/734...
8,9,tawfiktwins,183022,464,27234,1616935,238882,https://www.tiktok.com/@tawfiktwins/video/7438...
9,10,lojanoska,222030,1084,2433,1110202,230148,https://www.tiktok.com/@lojanoska/video/729884...

---
## 3. Extracción de vídeos - Europa

Búsquedas separadas por país: GB, ES, FR, DE. Se marca cada vídeo con su país de origen.

In [7]:
EU_COUNTRIES = [
    ("GB", "Reino Unido"),
    ("ES", "España"),
    ("FR", "Francia"),
    ("DE", "Alemania"),
]

items_europe = []

for code, nombre in EU_COUNTRIES:
    print(f"\nBuscando en {nombre} ({code})...")
    run_eu = client.actor("apidojo/tiktok-scraper").call(
        run_input={
            "startUrls": HASHTAG_URLS,
            "maxItems": 50,
            "location": code,
        }
    )
    items_country = list(client.dataset(run_eu["defaultDatasetId"]).iterate_items())
    for item in items_country:
        item["location_search"] = code
    items_europe.extend(items_country)
    print(f"  {nombre}: {len(items_country)} vídeos")

print(f"\nTotal vídeos Europa: {len(items_europe)}")

Buscando en Reino Unido (GB)...

[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> Status: RUNNING, Message:
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:51.765Z ACTOR: Pulling container image of build 1wgxHJCb5SrQmUuTk from registry.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:51.767Z ACTOR: Creating container.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:51.807Z ACTOR: Starting container.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.381Z INFO  System info {"apifyVersion":"3.4.2","apifyClientVersion":"2.12.4","crawleeVersion":"3.13.5","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.441Z INFO  PHASE -- STARTING ACTOR.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.798Z INFO  PHASE -- SETTING UP CRAWLER.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.798Z INFO  [Status message]: Your run has started.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.849Z WARN  ###############################
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.850Z WARN  Your run has started.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.851Z WARN  ###############################
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> Status: RUNNING, Message: Your run has started.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:53.851Z INFO  PHASE -- CRAWLER STARTED.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:56.363Z INFO  Got 19 videos for tag lululemonreview with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:57.364Z INFO  Got 19 videos for tag lululemon with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:57.692Z INFO  Got 18 videos for tag lululemonfinds with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:57.997Z INFO  Got 17 videos for tag lululemonreview with page: 2
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:58.394Z INFO  Got 19 videos for tag lululemonoutfit with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:58.823Z INFO  Got 18 videos for tag lululemonfavorites with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:59.036Z INFO  Got 20 videos for tag lululemontryhaul with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:42:59.086Z INFO  Got 16 videos for tag lululemonleggings with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:43:00.547Z INFO  Got 20 videos for tag lululemon with page: 2
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:43:00.718Z INFO  Got 20 videos for tag lululemonhaul with page: 1
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> 2026-03-26T12:43:00.720Z INFO  [Status message]: Your run has finished.
[apify.tiktok-scraper runId:xcCQsR9uyj1ngak1w] -> Status: SUCCEEDED, Message: Your run has finished.

  Reino Unido: 50 vídeos

Buscando en España (ES)...

[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> Status: RUNNING, Message:
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:08.843Z ACTOR: Pulling container image of build 1wgxHJCb5SrQmUuTk from registry.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:08.846Z ACTOR: Creating container.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:08.945Z ACTOR: Starting container.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.100Z INFO  System info {"apifyVersion":"3.4.2","apifyClientVersion":"2.12.4","crawleeVersion":"3.13.5","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.150Z INFO  PHASE -- STARTING ACTOR.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.457Z INFO  PHASE -- SETTING UP CRAWLER.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.458Z INFO  [Status message]: Your run has started.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.506Z WARN  ###############################
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.506Z WARN  Your run has started.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.507Z WARN  ###############################
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> Status: RUNNING, Message: Your run has started.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:11.507Z INFO  PHASE -- CRAWLER STARTED.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:14.316Z INFO  Got 19 videos for tag lululemonreview with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:14.385Z INFO  Got 18 videos for tag lululemonfinds with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:14.471Z INFO  Got 12 videos for tag lululemonleggings with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:15.245Z INFO  Got 4 videos for tag lululemonreview with page: 2
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:15.328Z INFO  Got 17 videos for tag lululemonoutfit with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:15.478Z INFO  Got 9 videos for tag lululemonfavorites with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:15.774Z INFO  Got 20 videos for tag lululemontryhaul with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:15.955Z INFO  Got 7 videos for tag lululemonleggings with page: 2
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:15.960Z INFO  Got 16 videos for tag lululemonfinds with page: 2
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:17.028Z INFO  Got 19 videos for tag lululemon with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:17.127Z INFO  Got 20 videos for tag lululemonhaul with page: 1
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> 2026-03-26T12:43:17.132Z INFO  [Status message]: Your run has finished.
[apify.tiktok-scraper runId:FIzY2pOAvQ3XHqj9C] -> Status: SUCCEEDED, Message: Your run has finished.

  España: 50 vídeos

Buscando en Francia (FR)...

[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> Status: RUNNING, Message:
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:25.833Z ACTOR: Pulling container image of build 1wgxHJCb5SrQmUuTk from registry.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:25.836Z ACTOR: Creating container.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:25.885Z ACTOR: Starting container.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.311Z INFO  System info {"apifyVersion":"3.4.2","apifyClientVersion":"2.12.4","crawleeVersion":"3.13.5","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.373Z INFO  PHASE -- STARTING ACTOR.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.690Z INFO  PHASE -- SETTING UP CRAWLER.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.691Z INFO  [Status message]: Your run has started.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.733Z WARN  ###############################
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.734Z WARN  Your run has started.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.735Z WARN  ###############################
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> Status: RUNNING, Message: Your run has started.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:27.736Z INFO  PHASE -- CRAWLER STARTED.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:29.835Z INFO  Got 18 videos for tag lululemonreview with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:31.165Z INFO  Got 20 videos for tag lululemonleggings with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:31.551Z INFO  Got 9 videos for tag lululemonfavorites with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:32.017Z INFO  Got 19 videos for tag lululemonoutfit with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:32.338Z INFO  Got 20 videos for tag lululemonhaul with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:32.512Z INFO  Got 15 videos for tag lululemonfinds with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:32.581Z INFO  Got 19 videos for tag lululemon with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:33.193Z INFO  Got 17 videos for tag lululemonreview with page: 2
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:35.100Z INFO  Got 0 videos for tag lululemonfavorites with page: 2
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:38.415Z INFO  Got 5 videos for tag lululemonleggings with page: 2
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:38.814Z INFO  Got 20 videos for tag lululemontryhaul with page: 1
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> Status: RUNNING, Message: Your run has finished.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> 2026-03-26T12:43:38.816Z INFO  [Status message]: Your run has finished.
[apify.tiktok-scraper runId:a4EIT8iCfWd4ooWeD] -> Status: SUCCEEDED, Message: Your run has finished.

  Francia: 50 vídeos

Buscando en Alemania (DE)...

[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> Status: RUNNING, Message:
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:47.501Z ACTOR: Pulling container image of build 1wgxHJCb5SrQmUuTk from registry.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:47.503Z ACTOR: Creating container.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:47.593Z ACTOR: Starting container.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.311Z INFO  System info {"apifyVersion":"3.4.2","apifyClientVersion":"2.12.4","crawleeVersion":"3.13.5","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.364Z INFO  PHASE -- STARTING ACTOR.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.819Z INFO  PHASE -- SETTING UP CRAWLER.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.820Z INFO  [Status message]: Your run has started.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.876Z WARN  ###############################
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.876Z WARN  Your run has started.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.877Z WARN  ###############################
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> Status: RUNNING, Message: Your run has started.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:49.877Z INFO  PHASE -- CRAWLER STARTED.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:52.071Z INFO  Got 19 videos for tag lululemon with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:52.098Z INFO  Got 12 videos for tag lululemonleggings with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:52.918Z INFO  Got 18 videos for tag lululemonfavorites with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:52.976Z INFO  Got 19 videos for tag lululemonoutfit with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:53.814Z INFO  Got 17 videos for tag lululemon with page: 2
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:53.867Z INFO  Got 17 videos for tag lululemonfinds with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:53.950Z INFO  Got 20 videos for tag lululemonhaul with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:53.952Z INFO  Got 7 videos for tag lululemonleggings with page: 2
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:54.607Z INFO  Got 14 videos for tag lululemonreview with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:55.924Z INFO  Got 20 videos for tag lululemontryhaul with page: 1
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> 2026-03-26T12:43:55.936Z INFO  [Status message]: Your run has finished.
[apify.tiktok-scraper runId:QS27oOmPAQQxYyx86] -> Status: SUCCEEDED, Message: Your run has finished.

  Alemania: 50 vídeos

Total vídeos Europa: 200

In [8]:
df_europe = procesar_videos(items_europe)

print(f"Total vídeos Europa: {len(df_europe)}")
if "location_search" in df_europe.columns:
    print(f"\nPor país de búsqueda:")
    print(df_europe["location_search"].value_counts())

print(f"\nTop 10 Europa por engagement:")
cols = ["rank", "author", "likes", "comments", "shares", "views", "score", "post_url"]
cols = [c for c in cols if c in df_europe.columns]
df_europe[cols].head(10)

Total vídeos Europa: 200

Por país de búsqueda:
location_search
FR    50
DE    50
GB    50
ES    50
Name: count, dtype: int64

Top 10 Europa por engagement:

,rank,author,likes,comments,shares,views,score,post_url
0,1,gabriella.a0,1242747,7130,31181,15533856,1326499,https://www.tiktok.com/@gabriella.a0/video/720...
1,2,gabriella.a0,1242394,7057,31183,15526016,1325931,https://www.tiktok.com/@gabriella.a0/video/720...
2,3,gabriella.a0,1242393,7057,31183,15526014,1325930,https://www.tiktok.com/@gabriella.a0/video/720...
3,4,alissa09082,881054,2852,20272,6236833,930154,https://www.tiktok.com/@alissa09082/video/7615...
4,5,alissa09082,881048,2852,20272,6236681,930148,https://www.tiktok.com/@alissa09082/video/7615...
5,6,itstookate,457639,5643,30343,3711479,535254,https://www.tiktok.com/@itstookate/video/76156...
6,7,itstookate,457639,5643,30343,3711495,535254,https://www.tiktok.com/@itstookate/video/76156...
7,8,athletikatyootd,451555,1001,1676,3515634,457910,https://www.tiktok.com/@athletikatyootd/video/...
8,9,bellagiannop,331023,1589,934,2448898,337658,https://www.tiktok.com/@bellagiannop/video/711...
9,10,bellagiannop,331023,1589,934,2448898,337658,https://www.tiktok.com/@bellagiannop/video/711...

---
## 4. Guardar vídeos y seleccionar top para extraer comentarios

In [9]:
df_us.to_csv("../datos/processed/tiktok/tiktok_lululemon_videos_US.csv", index=False, encoding="utf-8-sig")
df_europe.to_csv("../datos/processed/tiktok/tiktok_lululemon_videos_EUROPE.csv", index=False, encoding="utf-8-sig")

print("Guardados:")
print("  ../datos/processed/tiktok/tiktok_lululemon_videos_US.csv")
print("  ../datos/processed/tiktok/tiktok_lululemon_videos_EUROPE.csv")

Guardados:
  ../datos/processed/tiktok/tiktok_lululemon_videos_US.csv
  ../datos/processed/tiktok/tiktok_lululemon_videos_EUROPE.csv

In [10]:
N_TOP = 10

urls_us = df_us.head(N_TOP)["post_url"].dropna().tolist()
urls_europe = df_europe.head(N_TOP)["post_url"].dropna().tolist()

print(f"URLs seleccionadas US ({len(urls_us)}):")
for i, u in enumerate(urls_us, 1):
    print(f"  {i}. {u}")

print(f"\nURLs seleccionadas Europa ({len(urls_europe)}):")
for i, u in enumerate(urls_europe, 1):
    print(f"  {i}. {u}")

URLs seleccionadas US (10):
  1. https://www.tiktok.com/@huntercamp33/video/7200918254892649770
  2. https://www.tiktok.com/@lisi.shops/video/7266988919261285678
  3. https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
  4. https://www.tiktok.com/@8kzayy/video/7619882392978803981
  5. https://www.tiktok.com/@bellagiannop/video/7119551158422719787
  6. https://www.tiktok.com/@rose32xz/video/7552319724474912031
  7. https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
  8. https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
  9. https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
  10. https://www.tiktok.com/@lojanoska/video/7298843917066194218

URLs seleccionadas Europa (10):
  1. https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
  2. https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
  3. https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
  4. https://www.tiktok.com/@alissa09082/video/7615453695496441102
  5. https://www.tiktok.com/@alissa09082/video/7615453695496441102
  6. https://www.tiktok.com/@itstookate/video/7615661125551656223
  7. https://www.tiktok.com/@itstookate/video/7615661125551656223
  8. https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
  9. https://www.tiktok.com/@bellagiannop/video/7119551158422719787
  10. https://www.tiktok.com/@bellagiannop/video/7119551158422719787

---
## 5. Extracción de comentarios - Estados Unidos

Se extraen comentarios y luego se filtran a **solo inglés**.

In [11]:
MAX_COMMENTS = 200
MAX_REPLIES = 10

print(f"Extrayendo comentarios de {len(urls_us)} vídeos US...")

run_comments_us = client.actor("clockworks/tiktok-comments-scraper").call(
    run_input={
        "postURLs": urls_us,
        "maxComments": MAX_COMMENTS,
        "maxRepliesPerComment": MAX_REPLIES,
    }
)

print("Run ID:", run_comments_us["id"])
print("Dataset ID:", run_comments_us["defaultDatasetId"])

Extrayendo comentarios de 10 vídeos US...

[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> Status: RUNNING, Message:
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:03.305Z ACTOR: Pulling container image of build ESKgmPC1krhzsvwG3 from registry.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:03.307Z ACTOR: Creating container.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:03.371Z ACTOR: Starting container.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:03.373Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:03.554Z Running on architecture: x86_64
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:03.556Z Will run command: xvfb-run -a -s "-ac -screen 0 1920x1080x24+32 -nolisten tcp" /bin/bash -o pipefail -c bash -c "    java         --enable-native-access=ALL-UNNAMED         -cp classes-test:classes-main:lib/*         com.zhiliaoapp.musically.MetaSec         > /dev/null &     node dist/entrypoint.js "
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:04.369Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.22.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:05.017Z INFO  CheerioCrawler: Starting the crawler.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:05.860Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:05.862Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:05.897Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:05.914Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. [POST] Unable to fetch script from HTML, retrying request https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> Status: RUNNING, Message: Starting the crawler.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:05.916Z     at getScriptStrFromPage (file:///home/myuser/dist/tools/common-handler-tools.js:98:15) {"id":"ed9XbGnyS8sHFos","url":"https://www.tiktok.com/@sophiasouzas/video/7343234587000114475","retryCount":1}
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.146Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.149Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.161Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@lojanoska/video/7298843917066194218
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.164Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@lojanoska/video/7298843917066194218
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.183Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.185Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.190Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.203Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@lojanoska/video/7298843917066194218
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.222Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.362Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.364Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.399Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.579Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.581Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.610Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.648Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.650Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.663Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.665Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.680Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:06.756Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:07.081Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. [POST] Unable to fetch script from HTML, retrying request https://www.tiktok.com/@8kzayy/video/7619882392978803981
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:07.083Z     at getScriptStrFromPage (file:///home/myuser/dist/tools/common-handler-tools.js:98:15) {"id":"8wXGwuS5Ek2eFnR","url":"https://www.tiktok.com/@8kzayy/video/7619882392978803981","retryCount":1}
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:07.382Z INFO  Scraped 29 new comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:07.681Z INFO  Scraped 29 new comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:07.782Z INFO  Scraped 19 new comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:08.123Z INFO  Scraped 24 new comments. --- https://www.tiktok.com/@lojanoska/video/7298843917066194218
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:08.417Z INFO  Scraped 30 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:08.430Z INFO  Scraped 14 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:08.433Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:08.623Z INFO  Scraped 29 new comments. --- https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:08.911Z INFO  Scraped 4 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:09.606Z INFO  Scraped 29 new comments. --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:09.625Z INFO  Scraped 33 new comments. --- https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:09.974Z INFO  Scraped 12 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:10.087Z INFO  Scraped 16 new comments. --- https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:10.227Z INFO  Scraped 2 new comments. --- https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:10.318Z INFO  Scraped 12 new comments. --- https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:10.406Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:10.504Z INFO  Scraped 1 new comments. --- https://www.tiktok.com/@tiktokwithtay/video/6968899199773576453
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:11.149Z INFO  Scraped 17 new comments. --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:11.457Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:11.592Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:11.821Z INFO  Scraped 2 new comments. --- https://www.tiktok.com/@tawfiktwins/video/7438318483160501550
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:12.213Z INFO  Scraped 10 new comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:12.320Z INFO  Scraped 8 new comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:12.600Z INFO  Scraped 5 new comments. --- https://www.tiktok.com/@lisi.shops/video/7266988919261285678
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:12.813Z INFO  Scraped 23 new comments. --- https://www.tiktok.com/@lojanoska/video/7298843917066194218
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:12.963Z INFO  Scraped 19 new comments. --- https://www.tiktok.com/@lojanoska/video/7298843917066194218
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:12.979Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":5}}}
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:13.074Z INFO  Scraped 29 new comments. --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:13.252Z INFO  Scraped 8 new comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:13.699Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:13.734Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:14.033Z INFO  Scraped 10 new comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:14.117Z INFO  Scraped 4 new comments. --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:14.230Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:14.931Z INFO  [Status message]: Scraped 0/10 posts for top-level comments. Total comments scraped: 460.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> Status: RUNNING, Message: Crawled 45/252 pages, 0 failed requests, desired concurrency 10.
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:14.968Z INFO  Scraped 11 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:15.026Z INFO  Scraped 20 new comments. --- https://www.tiktok.com/@courtneyycahoon/video/7173826000139144494
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:15.173Z INFO  Scraped 9 new comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:15.283Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:15.388Z INFO  Scraped 4 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:15.506Z INFO  Scraped 15 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:15.655Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:16.211Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":1}}}
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:16.711Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:16.714Z INFO  Scraped 7 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:16.795Z INFO  Scraped 11 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:16.886Z INFO  Scraped 17 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:16.981Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:17.061Z INFO  Scraped 9 new comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:17.063Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:17.162Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:17.653Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:17.989Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:18.206Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:18.281Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:18.354Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:18.484Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:18.551Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:18.689Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:19.008Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:19.081Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:19.316Z INFO  Scraped 9 new reply comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:19.496Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:19.498Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@rose32xz/video/7552319724474912031
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:19.952Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:20.574Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:20.591Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770
[apify.tiktok-comments-scraper runId:FZ51cpF3fJqWOzO3H] -> 2026-03-26T12:44:20.611Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@huntercamp33/video/7200918254892649770

Run ID: FZ51cpF3fJqWOzO3H
Dataset ID: OOGNuLDsJhkPPOaHg

In [12]:
comments_us_raw = list(client.dataset(run_comments_us["defaultDatasetId"]).iterate_items())
print(f"Total comentarios US (sin filtrar): {len(comments_us_raw)}")

df_comments_us_raw = pd.DataFrame(comments_us_raw)

# Filtrar: solo inglés para US
print("\n--- Filtro de idioma US: solo inglés ---")
df_comments_us = filtrar_comentarios_por_idioma(df_comments_us_raw, ["en"])

Total comentarios US (sin filtrar): 1000

--- Filtro de idioma US: solo inglés ---
Distribución de idiomas detectados:
idioma_detectado
en         693
unknown     26
cy          24
so          23
de          19
fr          19
id          19
ro          16
tr          14
af          14
Name: count, dtype: int64

Comentarios antes del filtro: 1000
Comentarios después del filtro (en): 693

In [13]:
# Guardar comentarios filtrados
comments_us = df_comments_us.to_dict(orient="records")

with open("../datos/processed/tiktok/tiktok_lululemon_comentarios_US.json", "w", encoding="utf-8") as f:
    json.dump(comments_us, f, ensure_ascii=False, indent=4)

df_comments_us.to_csv("../datos/processed/tiktok/tiktok_lululemon_comentarios_US.csv", index=False, encoding="utf-8-sig")

print(f"Guardado: {len(df_comments_us)} comentarios en inglés")
print("  ../datos/processed/tiktok/tiktok_lululemon_comentarios_US.csv / .json")

Guardado: 693 comentarios en inglés
  ../datos/processed/tiktok/tiktok_lululemon_comentarios_US.csv / .json

---
## 6. Extracción de comentarios - Europa

Se extraen comentarios de los top vídeos europeos y se filtran por idioma del país:
- GB → inglés
- ES → español
- FR → francés
- DE → alemán

In [14]:
# Mapeo de país de búsqueda → idiomas permitidos en los comentarios
IDIOMAS_POR_PAIS = {
    "GB": ["en"],
    "ES": ["es"],
    "FR": ["fr"],
    "DE": ["de"],
}

# Extraer comentarios por país para poder filtrar por idioma
all_comments_eu = []

for code, nombre in EU_COUNTRIES:
    # Seleccionar top vídeos de este país
    df_pais = df_europe[df_europe["location_search"] == code].copy()
    if len(df_pais) == 0:
        print(f"\n{nombre} ({code}): sin vídeos, saltando.")
        continue
    
    urls_pais = df_pais.head(5)["post_url"].dropna().tolist()  # top 5 por país
    if not urls_pais:
        print(f"\n{nombre} ({code}): sin URLs válidas, saltando.")
        continue
    
    print(f"\n{'='*50}")
    print(f"{nombre} ({code}): extrayendo comentarios de {len(urls_pais)} vídeos...")
    
    run_eu = client.actor("clockworks/tiktok-comments-scraper").call(
        run_input={
            "postURLs": urls_pais,
            "maxComments": MAX_COMMENTS,
            "maxRepliesPerComment": MAX_REPLIES,
        }
    )
    
    items_comments = list(client.dataset(run_eu["defaultDatasetId"]).iterate_items())
    print(f"  Comentarios extraídos (sin filtrar): {len(items_comments)}")
    
    if len(items_comments) == 0:
        continue
    
    df_temp = pd.DataFrame(items_comments)
    
    # Filtrar por idioma del país
    idiomas = IDIOMAS_POR_PAIS.get(code, ["en"])
    print(f"  Filtro de idioma: {idiomas}")
    df_filtrado = filtrar_comentarios_por_idioma(df_temp, idiomas)
    
    # Marcar el país de origen
    df_filtrado["pais_busqueda"] = code
    all_comments_eu.append(df_filtrado)

# Juntar todos los comentarios europeos
if all_comments_eu:
    df_comments_eu = pd.concat(all_comments_eu, ignore_index=True)
else:
    df_comments_eu = pd.DataFrame()

print(f"\n{'='*50}")
print(f"Total comentarios Europa (filtrados por idioma): {len(df_comments_eu)}")
if "pais_busqueda" in df_comments_eu.columns:
    print(df_comments_eu["pais_busqueda"].value_counts())

==================================================
Reino Unido (GB): extrayendo comentarios de 5 vídeos...

[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> Status: RUNNING, Message:
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:47.579Z ACTOR: Pulling container image of build ESKgmPC1krhzsvwG3 from registry.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:47.581Z ACTOR: Creating container.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:47.694Z ACTOR: Starting container.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:47.696Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:47.906Z Running on architecture: x86_64
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:47.906Z Will run command: xvfb-run -a -s "-ac -screen 0 1920x1080x24+32 -nolisten tcp" /bin/bash -o pipefail -c bash -c "    java         --enable-native-access=ALL-UNNAMED         -cp classes-test:classes-main:lib/*         com.zhiliaoapp.musically.MetaSec         > /dev/null &     node dist/entrypoint.js "
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:49.356Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.22.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> Status: RUNNING, Message: Starting the crawler.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:49.843Z INFO  CheerioCrawler: Starting the crawler.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.182Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.183Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.199Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.200Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.221Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.232Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.698Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.699Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.728Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.859Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.859Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:51.902Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:52.101Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:52.102Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:52.130Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.296Z INFO  Scraped 33 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.412Z INFO  Scraped 15 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.446Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.564Z INFO  Scraped 31 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.763Z INFO  Scraped 32 new comments. --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.785Z INFO  Scraped 32 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.831Z INFO  Scraped 3 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:53.943Z INFO  Scraped 30 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:54.183Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:55.161Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:55.258Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:55.457Z INFO  Scraped 9 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:55.533Z INFO  Scraped 18 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:55.675Z INFO  Scraped 3 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:55.937Z INFO  Scraped 10 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:55.970Z INFO  Scraped 4 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:56.310Z INFO  Scraped 4 new comments. --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:56.448Z INFO  Scraped 1 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:56.585Z INFO  Scraped 9 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:56.959Z INFO  Scraped 5 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:56.973Z INFO  Scraped 1 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:57.002Z INFO  Scraped 1 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:57.287Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:57.330Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:57.405Z INFO  Scraped 18 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:57.603Z INFO  Scraped 11 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:57.974Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:58.371Z INFO  Scraped 7 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:58.383Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:58.488Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:58.648Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:58.925Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.044Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.124Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.389Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.745Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.747Z INFO  [Status message]: Scraped 0/5 posts for top-level comments. Total comments scraped: 283.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.833Z INFO  Scraped 19 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.848Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.979Z INFO  Scraped 8 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:45:59.991Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> Status: RUNNING, Message: Crawled 43/206 pages, 0 failed requests, desired concurrency 10.
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:00.107Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:00.549Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:00.551Z INFO  Scraped 4 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:00.741Z INFO  Scraped 8 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.094Z INFO  Scraped 9 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.300Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.304Z INFO  Scraped 10 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.445Z INFO  Scraped 12 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.446Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.449Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.522Z INFO  Scraped 7 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:01.953Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:02.072Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:02.253Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:02.523Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:02.607Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.056Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.077Z INFO  Scraped 18 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.078Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.083Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.114Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":1}}}
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.349Z INFO  Scraped 14 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.433Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:03.879Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:04.030Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:04.253Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:04.403Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:04.417Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:04.563Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:04.686Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:05.309Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:05.630Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:05.701Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:05.718Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:05.834Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:05.838Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:06.152Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:06.305Z INFO  Scraped 12 new comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:06.305Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:06.905Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:F66w5uEW7hEySGv0W] -> 2026-03-26T12:46:07.049Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814

  Comentarios extraídos (sin filtrar): 500
  Filtro de idioma: ['en']
Distribución de idiomas detectados:
idioma_detectado
en         316
unknown     29
de          27
ro          13
cy          12
fr          11
so          11
es          11
af           9
ca           8
Name: count, dtype: int64

Comentarios antes del filtro: 500
Comentarios después del filtro (en): 316

==================================================
España (ES): extrayendo comentarios de 5 vídeos...

[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> Status: RUNNING, Message:
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:47.617Z ACTOR: Pulling container image of build ESKgmPC1krhzsvwG3 from registry.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:47.619Z ACTOR: Creating container.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:47.661Z ACTOR: Starting container.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:47.662Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:47.845Z Running on architecture: x86_64
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:47.845Z Will run command: xvfb-run -a -s "-ac -screen 0 1920x1080x24+32 -nolisten tcp" /bin/bash -o pipefail -c bash -c "    java         --enable-native-access=ALL-UNNAMED         -cp classes-test:classes-main:lib/*         com.zhiliaoapp.musically.MetaSec         > /dev/null &     node dist/entrypoint.js "
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:49.077Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.22.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> Status: RUNNING, Message: Starting the crawler.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:49.570Z INFO  CheerioCrawler: Starting the crawler.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.617Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.618Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.664Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.907Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.908Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.917Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.919Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.947Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:50.958Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:51.680Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:51.681Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:51.723Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:53.083Z INFO  Scraped 29 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:53.358Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:53.445Z INFO  Scraped 38 new comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:53.541Z INFO  Scraped 8 new comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:53.698Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:53.923Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":5}}}
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:53.949Z INFO  Scraped 30 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:54.554Z INFO  Scraped 16 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:54.852Z INFO  Scraped 8 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:55.355Z INFO  Scraped 2 new comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:55.788Z INFO  Scraped 27 new comments. --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:55.850Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:55.941Z INFO  Scraped 4 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:56.103Z INFO  Scraped 1 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:56.366Z INFO  Scraped 2 new comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:56.410Z INFO  Scraped 1 new comments. --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:57.612Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:57.970Z INFO  Scraped 15 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:58.317Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":5}}}
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:58.325Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:58.433Z INFO  Scraped 16 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:58.710Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:58.874Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:58.881Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:59.304Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:59.506Z INFO  [Status message]: Scraped 0/5 posts for top-level comments. Total comments scraped: 213.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:59.516Z INFO  Scraped 4 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:59.969Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:46:59.970Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> Status: RUNNING, Message: Crawled 30/102 pages, 0 failed requests, desired concurrency 10.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:00.356Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:00.611Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:00.791Z INFO  Scraped 10 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:00.792Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:00.804Z INFO  Scraped 1 new comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:01.253Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:01.563Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:01.568Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:01.925Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:02.404Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":1}}}
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:02.686Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:02.739Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:03.023Z INFO  Scraped 5 new comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:03.415Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:03.810Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:03.865Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:03.900Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:04.024Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:04.200Z INFO  Scraped 4 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:04.313Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.057Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.480Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.542Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.543Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@joslifevidz/video/7521379638371798303
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.620Z INFO  Scraped 14 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.845Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.894Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:05.951Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:06.328Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:06.742Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:06.893Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:06.981Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":1}}}
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:07.008Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:07.068Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:07.356Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:07.555Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:07.804Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:07.910Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:08.570Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:08.684Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:08.771Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@nicoleee271/video/7182625983449533742
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.002Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.284Z INFO  Scraped 20 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.285Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.506Z INFO  [Status message]: Scraped 0/5 posts for top-level comments. Total comments scraped: 225.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.685Z INFO  Scraped 15 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.687Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.912Z INFO  Scraped 14 new comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.913Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:09.929Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:10.118Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@hintofnattyp/video/7367545064760937770
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> Status: RUNNING, Message: Crawled 72/109 pages, 0 failed requests, desired concurrency 11.
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:10.413Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:10.716Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:10.819Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@djanelleshops/video/7560437457456549131
[apify.tiktok-comments-scraper runId:V7OftPTTHAqK1jWjZ] -> 2026-03-26T12:47:10.967Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":1}}}

  Comentarios extraídos (sin filtrar): 400
  Filtro de idioma: ['es']
Distribución de idiomas detectados:
idioma_detectado
en         298
unknown     24
ro          20
so           7
tl           7
cy           7
it           5
nl           4
et           4
de           3
Name: count, dtype: int64

Comentarios antes del filtro: 400
Comentarios después del filtro (es): 0

==================================================
Francia (FR): extrayendo comentarios de 5 vídeos...

[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> Status: RUNNING, Message:
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:09.559Z ACTOR: Pulling container image of build ESKgmPC1krhzsvwG3 from registry.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:09.562Z ACTOR: Creating container.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:09.730Z ACTOR: Starting container.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:09.731Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:09.903Z Running on architecture: x86_64
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:09.906Z Will run command: xvfb-run -a -s "-ac -screen 0 1920x1080x24+32 -nolisten tcp" /bin/bash -o pipefail -c bash -c "    java         --enable-native-access=ALL-UNNAMED         -cp classes-test:classes-main:lib/*         com.zhiliaoapp.musically.MetaSec         > /dev/null &     node dist/entrypoint.js "
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:10.725Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.22.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> Status: RUNNING, Message: Starting the crawler.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:11.259Z INFO  CheerioCrawler: Starting the crawler.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.496Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.498Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.548Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.742Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.744Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.758Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.760Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.787Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.796Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.997Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:12.999Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:13.030Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:13.232Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:13.234Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:13.303Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.352Z INFO  Scraped 33 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.405Z INFO  Scraped 28 new comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.445Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.579Z INFO  Scraped 31 new comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.594Z INFO  Scraped 8 new comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.690Z INFO  Scraped 12 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.700Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:14.750Z INFO  Scraped 28 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:15.590Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:15.987Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:16.019Z INFO  Scraped 12 new comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:16.365Z INFO  Scraped 3 new comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:16.382Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":5}}}
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:16.429Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:16.559Z INFO  Scraped 12 new comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:16.921Z INFO  Scraped 2 new comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:16.961Z INFO  Scraped 3 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:17.312Z INFO  Scraped 33 new comments. --- https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:17.317Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:17.654Z INFO  Scraped 6 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:18.069Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:18.117Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":5}}}
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:18.178Z INFO  Scraped 22 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:18.386Z INFO  Scraped 2 new comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:18.397Z INFO  Scraped 9 new comments. --- https://www.tiktok.com/@sophiasouzas/video/7343234587000114475
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:18.767Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:18.833Z INFO  Scraped 16 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:19.177Z INFO  Scraped 13 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:19.272Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:19.406Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:20.035Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:20.126Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:20.434Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:20.488Z INFO  Scraped 15 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:20.584Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:20.678Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:20.912Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:21.132Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:21.164Z INFO  [Status message]: Scraped 0/5 posts for top-level comments. Total comments scraped: 312.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> Status: RUNNING, Message: Crawled 43/160 pages, 0 failed requests, desired concurrency 10.
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:21.388Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:21.683Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:21.725Z INFO  Scraped 4 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:21.823Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:21.954Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:22.019Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:22.114Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:22.497Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:22.891Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.010Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.079Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.369Z INFO  Scraped 15 new comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.541Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.577Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.593Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.601Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.828Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.916Z INFO  Scraped 21 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:23.918Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:24.335Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:24.726Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":1}}}
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:24.763Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:24.836Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:24.880Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:24.930Z INFO  Scraped 15 new comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:24.978Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:25.117Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@athletikatyootd/video/7007921382730272006
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:25.298Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:25.520Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:25.569Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@mjsfashiondiary/video/7150348762849004805
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:25.795Z INFO  Scraped 8 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:25.797Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:26.104Z INFO  Scraped 18 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:26.515Z INFO  Scraped 15 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:26.560Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:26.587Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:26.696Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:26.741Z INFO  Scraped 19 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:26.847Z INFO  Scraped 13 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:27.340Z INFO  Scraped 18 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:27.698Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:U8qxAzNS9zyCAPLuX] -> 2026-03-26T12:48:27.832Z INFO  Scraped 8 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539

  Comentarios extraídos (sin filtrar): 500
  Filtro de idioma: ['fr']
Distribución de idiomas detectados:
idioma_detectado
en         303
unknown     22
es          17
fr          14
so          14
ro          13
cy          13
de          10
tl          10
no           9
Name: count, dtype: int64

Comentarios antes del filtro: 500
Comentarios después del filtro (fr): 14

==================================================
Alemania (DE): extrayendo comentarios de 5 vídeos...

[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> Status: RUNNING, Message: Starting the crawler.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:49.819Z ACTOR: Pulling container image of build ESKgmPC1krhzsvwG3 from registry.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:49.829Z ACTOR: Creating container.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:49.864Z ACTOR: Starting container.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:49.864Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:50.093Z Running on architecture: x86_64
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:50.094Z Will run command: xvfb-run -a -s "-ac -screen 0 1920x1080x24+32 -nolisten tcp" /bin/bash -o pipefail -c bash -c "    java         --enable-native-access=ALL-UNNAMED         -cp classes-test:classes-main:lib/*         com.zhiliaoapp.musically.MetaSec         > /dev/null &     node dist/entrypoint.js "
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:51.292Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.22.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:51.906Z INFO  CheerioCrawler: Starting the crawler.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:52.770Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:52.770Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:52.811Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:52.832Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. [POST] Unable to fetch script from HTML, retrying request https://www.tiktok.com/@alissa09082/video/7615453695496441102
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:52.833Z     at getScriptStrFromPage (file:///home/myuser/dist/tools/common-handler-tools.js:98:15) {"id":"mm6tfoeD7F2TKHC","url":"https://www.tiktok.com/@alissa09082/video/7615453695496441102","retryCount":1}
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:53.015Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:53.016Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:53.049Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:53.222Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:53.223Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:53.262Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:54.917Z INFO  Scraped 35 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:54.995Z INFO  Scraped 7 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:55.052Z INFO  Scraped 30 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:55.096Z INFO  Scraped 33 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:55.113Z INFO  Scraped 11 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:55.191Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:55.202Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:55.350Z INFO  Scraped 2 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:56.030Z INFO  [POST] Starting the post scrape.  --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:56.030Z INFO  [POST] Starting the comments scrape.  --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:56.066Z INFO  [POST] Post scraped successfully.  --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:56.079Z INFO  Scraped 3 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:56.487Z INFO  Scraped 16 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:57.432Z INFO  Scraped 8 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:57.517Z INFO  Scraped 19 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:57.795Z INFO  Scraped 31 new comments. --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:57.815Z INFO  Scraped 13 new comments. --- https://www.tiktok.com/@catwhisperer2007/video/7606015163107478814
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:58.407Z WARN  Blocked response, retrying... {"attempt":1,"paginationInfo":{"cursor":"0","index":0,"batchInfo":{"batchIndex":0,"batchSize":5}}}
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:58.747Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:48:59.002Z INFO  Scraped 4 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:00.043Z INFO  Scraped 11 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:00.448Z INFO  Scraped 19 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:00.467Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:01.274Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:01.551Z INFO  Scraped 11 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:01.568Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:01.680Z INFO  Scraped 22 new comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> Status: RUNNING, Message: Crawled 31/146 pages, 0 failed requests, desired concurrency 10.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:01.822Z INFO  [Status message]: Scraped 0/5 posts for top-level comments. Total comments scraped: 237.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:02.376Z INFO  Scraped 9 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:02.739Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:03.813Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:04.637Z INFO  Scraped 11 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:04.683Z INFO  Scraped 19 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:04.811Z INFO  Scraped 13 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:05.601Z INFO  Scraped 13 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:05.642Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:06.358Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:06.971Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:07.634Z INFO  Scraped 8 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:07.645Z INFO  Scraped 24 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:07.645Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:07.727Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:07.735Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:07.864Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:07.982Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:08.900Z INFO  Scraped 7 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:09.112Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:09.387Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:10.136Z INFO  Scraped 13 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:10.270Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:10.421Z INFO  Scraped 4 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:10.717Z INFO  Scraped 15 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:10.721Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:11.524Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> Status: RUNNING, Message: Crawled 57/147 pages, 0 failed requests, desired concurrency 11.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:11.821Z INFO  [Status message]: Scraped 0/5 posts for top-level comments. Total comments scraped: 237.
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:12.166Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:12.188Z INFO  Scraped 22 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:12.189Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:12.618Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:13.283Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:13.297Z INFO  Scraped 16 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:13.777Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:14.017Z INFO  Scraped 7 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:14.302Z INFO  Scraped 6 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:14.353Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:15.370Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.017Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.107Z INFO  Scraped 21 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.109Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.112Z INFO  Scraped 22 new comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.113Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.203Z INFO  Scraped 1 new reply comments. --- https://www.tiktok.com/@bellagiannop/video/7119551158422719787
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.210Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.384Z INFO  Scraped 24 new comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.385Z WARN  The post has no more top-level comments to scrape. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:16.980Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:17.116Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@itstookate/video/7615661125551656223
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:17.205Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:17.706Z INFO  Scraped 15 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:18.341Z INFO  Scraped 5 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:18.412Z INFO  Scraped 12 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:18.679Z INFO  Scraped 2 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:19.092Z INFO  Scraped 3 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:19.184Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539
[apify.tiktok-comments-scraper runId:QSEknpISjzmrwayJq] -> 2026-03-26T12:49:19.206Z INFO  Scraped 20 new reply comments. --- https://www.tiktok.com/@gabriella.a0/video/7209474725054090539

  Comentarios extraídos (sin filtrar): 500
  Filtro de idioma: ['de']
Distribución de idiomas detectados:
idioma_detectado
en         303
de          33
unknown     22
ro          15
cy          14
es          12
fr          11
so           9
nl           8
fi           7
Name: count, dtype: int64

Comentarios antes del filtro: 500
Comentarios después del filtro (de): 33

==================================================
Total comentarios Europa (filtrados por idioma): 363
pais_busqueda
GB    316
DE     33
FR     14
Name: count, dtype: int64

In [15]:
# Guardar comentarios Europa filtrados
comments_eu = df_comments_eu.to_dict(orient="records")

with open("../datos/processed/tiktok/tiktok_lululemon_comentarios_EUROPE.json", "w", encoding="utf-8") as f:
    json.dump(comments_eu, f, ensure_ascii=False, indent=4)

df_comments_eu.to_csv("../datos/processed/tiktok/tiktok_lululemon_comentarios_EUROPE.csv", index=False, encoding="utf-8-sig")

print(f"Guardado: {len(df_comments_eu)} comentarios filtrados por idioma")
print("  ../datos/processed/tiktok/tiktok_lululemon_comentarios_EUROPE.csv / .json")

Guardado: 363 comentarios filtrados por idioma
  ../datos/processed/tiktok/tiktok_lululemon_comentarios_EUROPE.csv / .json

---
## 7. Resumen final

In [16]:
print("="*60)
print("RESUMEN DE EXTRACCIÓN")
print("="*60)
print(f"\nVídeos encontrados:")
print(f"  US:     {len(df_us)} vídeos")
print(f"  Europa: {len(df_europe)} vídeos")
print(f"\nComentarios extraídos (filtrados por idioma):")
print(f"  US (inglés):  {len(df_comments_us)} comentarios")
print(f"  Europa:       {len(df_comments_eu)} comentarios")
if "pais_busqueda" in df_comments_eu.columns:
    for code, nombre in EU_COUNTRIES:
        n = len(df_comments_eu[df_comments_eu["pais_busqueda"] == code])
        idioma = IDIOMAS_POR_PAIS.get(code, ["?"])[0]
        print(f"    {nombre} ({idioma}): {n}")
print(f"\nArchivos generados:")
print(f"  ../datos/processed/tiktok/tiktok_lululemon_videos_US.csv")
print(f"  ../datos/processed/tiktok/tiktok_lululemon_videos_EUROPE.csv")
print(f"  ../datos/processed/tiktok/tiktok_lululemon_comentarios_US.csv / .json")
print(f"  ../datos/processed/tiktok/tiktok_lululemon_comentarios_EUROPE.csv / .json")

============================================================
RESUMEN DE EXTRACCIÓN
============================================================

Vídeos encontrados:
  US:     200 vídeos
  Europa: 200 vídeos

Comentarios extraídos (filtrados por idioma):
  US (inglés):  693 comentarios
  Europa:       363 comentarios
    Reino Unido (en): 316
    España (es): 0
    Francia (fr): 14
    Alemania (de): 33

Archivos generados:
  ../datos/processed/tiktok/tiktok_lululemon_videos_US.csv
  ../datos/processed/tiktok/tiktok_lululemon_videos_EUROPE.csv
  ../datos/processed/tiktok/tiktok_lululemon_comentarios_US.csv / .json
  ../datos/processed/tiktok/tiktok_lululemon_comentarios_EUROPE.csv / .json